[package]
name = "noisy_float"
version = "0.1.2"
authors = ["Matthew Michelotti <matthew@matthewmichelotti.com>"]
description = "Contains floating point types that panic if they are set to an illegal value, such as NaN"
documentation = "https://docs.rs/noisy_float"
repository = "https://github.com/SergiusIW/noisy_float-rs"
readme = "README.md"
keywords = ["float", "signaling", "NaN", "finite", "panic"]
license = "Apache-2.0"

[dependencies]
num-traits = "^0.1.35"
approx = "^0.1.1"
alga = { version = "^0.5.2", optional = true }
alga_derive = { version = "^0.5.1", optional = true }

[features]
algebra = ["alga", "alga_derive"]
